# Generated by Django 4.1.2 on 2022-10-15 16:31

from django.db import migrations


def convert_line_to_values(line):
    elements = line.strip().split(",")
    return elements


def add_data_from_csv(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    with open("polls/migrations/questions.csv") as f:
        for i, line in enumerate(f):
            if i == 0:  # skip column names
                continue
            values = convert_line_to_values(line)
            question = Question(question_text=values[0], pub_date=values[1])
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data_from_csv)
    ]
